pre 1.1.0.0
AntinomyCollective/Retime-Phoneme-Util-GUI pull request #2
Opened 2023-01-14 17:02 UTC by stamepicmorg

fixed ui
fixed logic

2023-01-14 17:02 UTC, stamepicmorg commented
i think some code needs to optimisations. i am lazy a bit.

2023-01-15 05:47 UTC, kasthack requested changes
![image](https://user-images.githubusercontent.com/1292818/212524974-c88a85ca-3771-4cb0-a0dc-80f79867a52b.png)

2023-01-15 05:47 UTC, kasthack commented on src/kru.gui/Command.cs
> +            Application.Restart();
Зачем?

2023-01-15 05:47 UTC, kasthack commented on src/kru.gui/Command.cs
> +            return null!;
Аналогично

2023-01-15 05:47 UTC, kasthack commented on src/kru.gui/frmAbout.cs
> +            if (Environment.Is64BitProcess == true && Environment.Is64BitOperatingSystem == true)
- Зачем сравнивать non-nullable boolean с true?
- Второе условие не может вернуть false, если выполнилось первое -- лишняя проверка.

2023-01-15 05:47 UTC, kasthack commented on src/kru.gui/frmAbout.cs
> +        public void bitness()
Нейминг

2023-01-15 05:47 UTC, kasthack commented on src/kru.gui/frmAbout.cs
> +        public string archbitness = "x86";
- Зачем это является полем?
- Зачем тут дефолтное значение, если всё равно устанавливается ниже?

2023-01-15 05:47 UTC, kasthack commented on src/kru.gui/frmAbout.cs
> +            Process myProcess = new Process();
Зачем дублировать функцию N раз, если меняется один параметр? Use [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself), Luke.

2023-01-15 05:47 UTC, kasthack commented on src/kru.gui/frmAbout.cs
> +            Process myProcess = new Process();
Коммент про дубль выше

2023-01-15 05:47 UTC, kasthack commented on src/kru.gui/frmAbout.cs
> +            Process myProcess = new Process();
Коммент про дубль выше

2023-01-15 05:47 UTC, kasthack commented on src/kru.gui/frmAbout.cs
> +            Process myProcess = new Process();
Коммент про дубль выше

2023-01-15 05:47 UTC, kasthack commented on src/kru.gui/frmAbout.cs
> +                Console.WriteLine(ex.Message);
Приложение не консольное и никто не увидит вывод. В чём смысл этого вызова?

2023-01-15 05:47 UTC, kasthack commented on src/kru.gui/Command.cs
> +            @"Tools\"+ Bitness + @"\retime_phoneme.exe"
Зачем выносить в параметр, а не делать частью команды?

2023-01-15 05:47 UTC, kasthack commented on src/kru.gui/Command.cs
> +        catch (Exception ex)
Исключение никогда не произойдёт, ветка бесполезна

2023-01-15 05:47 UTC, kasthack commented on src/kru.gui/frmAbout.cs
> +            var appVer = Assembly.GetEntryAssembly()!.GetCustomAttribute<AssemblyInformationalVersionAttribute>()!.InformationalVersion;
Трижды получается сборка, что ресурсозатратно. Assembly, вроде, ещё и IDisposable.

2023-01-15 05:47 UTC, kasthack commented on src/kru.gui/frmMain.cs
> +            //&& Directory.Exists(this.txtOutputClean.Text)
Зачем этот комментарий?

2023-01-15 05:47 UTC, kasthack commented on src/kru.gui/frmMain.cs
> +        var frmabout = new frmAbout();
IDisposable не освобождается

2023-01-15 05:47 UTC, kasthack commented on src/kru.gui/Command.cs
> +internal record Command(string InputFile, string OutputFile, string OutputFileClean, bool Clean, bool SaveLog,string Bitness)
- `OutputFileClean` — nullable, тогда можно избавиться от дублирования в Clean. Возможно, вообще переписать на `OutputDirectory`, `CleanDirectory`, чтобы пути в caller'е не считать, размазывая логику.
- bitness прибита к параметрам системы и не редактируется пользователем. Не должна быть параметром.

2023-01-15 06:03 UTC, kasthack commented
Отдельно от PR, т.к. правки были добавлены раньше:

1. В чём смысл файлика build.bat?
   - Инженеры майкрософта специально мультитаргетинг прикрутили, чтоб такие срипты не нужно было писать.
   - Параметры дублируют настройки из csproj — аналогично.
   - Собираться под 32 бита в 2023 — ну, хз. Steam survey [показывает](https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam) аж 0.11% пользователей на 32-битных ОС.

2023-01-15 08:43 UTC, stamepicmorg commented on src/kru.gui/Command.cs
> +            Application.Restart();
забей. если условие не выполнится, то пофиг.

2023-01-15 08:44 UTC, stamepicmorg commented on src/kru.gui/Command.cs
> +            return null!;
Аналогично

2023-01-15 08:44 UTC, kasthack commented on src/kru.gui/Command.cs
> +            Application.Restart();
Fixed @ 000000001de5219a1adb06e76a6e37230c334ac0

2023-01-15 08:44 UTC, kasthack commented on src/kru.gui/frmAbout.cs
> +        public void bitness()
Fixed @ 000000001de5219a1adb06e76a6e37230c334ac0

2023-01-15 08:44 UTC, kasthack commented on src/kru.gui/Command.cs
> +        catch (Exception ex)
Fixed @ 000000001de5219a1adb06e76a6e37230c334ac0

2023-01-15 08:44 UTC, kasthack commented on src/kru.gui/frmMain.cs
> +        var frmabout = new frmAbout();
Fixed @ 000000001de5219a1adb06e76a6e37230c334ac0

2023-01-15 08:44 UTC, kasthack commented on src/kru.gui/Command.cs
> +internal record Command(string InputFile, string OutputFile, string OutputFileClean, bool Clean, bool SaveLog,string Bitness)
Fixed @ 000000001de5219a1adb06e76a6e37230c334ac0

2023-01-15 08:44 UTC, kasthack commented on src/kru.gui/frmAbout.cs
> +            var appVer = Assembly.GetEntryAssembly()!.GetCustomAttribute<AssemblyInformationalVersionAttribute>()!.InformationalVersion;
Fixed @ 000000001de5219a1adb06e76a6e37230c334ac0

2023-01-15 08:44 UTC, kasthack commented on src/kru.gui/frmMain.cs
> +            //&& Directory.Exists(this.txtOutputClean.Text)
Fixed @ 000000001de5219a1adb06e76a6e37230c334ac0

2023-01-15 08:44 UTC, stamepicmorg commented on src/kru.gui/frmAbout.cs
> +            if (Environment.Is64BitProcess == true && Environment.Is64BitOperatingSystem == true)
оно возвращает false если бинарь 32хбитный на 64хбитной системе. с учетом мультисборки, то такое возможно.

проверял.

и мне надо совпадениео обоих условий.

2023-01-15 08:45 UTC, stamepicmorg commented on src/kru.gui/frmAbout.cs
> +        public void bitness()
согласен

2023-01-15 08:45 UTC, kasthack commented on src/kru.gui/frmAbout.cs
> +        public string archbitness = "x86";
Fixed @ 000000001de5219a1adb06e76a6e37230c334ac0

2023-01-15 08:45 UTC, kasthack commented on src/kru.gui/frmAbout.cs
> +            if (Environment.Is64BitProcess == true && Environment.Is64BitOperatingSystem == true)
Fixed @ 000000001de5219a1adb06e76a6e37230c334ac0

2023-01-15 08:45 UTC, kasthack commented on src/kru.gui/Command.cs
> +            return null!;
Fixed @ 000000001de5219a1adb06e76a6e37230c334ac0

2023-01-15 08:45 UTC, stamepicmorg commented on src/kru.gui/frmAbout.cs
> +        public string archbitness = "x86";
а как сделать правильно? мои знания шарпа 10тилетней давности

2023-01-15 08:45 UTC, stamepicmorg commented on src/kru.gui/Command.cs
> +        catch (Exception ex)
даже если папка tools будет отсутствовать?:

2023-01-15 08:46 UTC, stamepicmorg commented on src/kru.gui/frmAbout.cs
> +            var appVer = Assembly.GetEntryAssembly()!.GetCustomAttribute<AssemblyInformationalVersionAttribute>()!.InformationalVersion;
я не столь прошареный за подкапотные игры. но доверюсь тебе.

2023-01-15 08:46 UTC, kasthack commented on src/kru.gui/Command.cs
> +            @"Tools\"+ Bitness + @"\retime_phoneme.exe"
Fixed @ 000000001de5219a1adb06e76a6e37230c334ac0

2023-01-15 08:46 UTC, kasthack commented on src/kru.gui/frmAbout.cs
> +                Console.WriteLine(ex.Message);
Fixed @ 000000001de5219a1adb06e76a6e37230c334ac0

2023-01-15 08:46 UTC, stamepicmorg commented on src/kru.gui/frmMain.cs
> +            //&& Directory.Exists(this.txtOutputClean.Text)
писал в своем сообщение в начале pr.

2023-01-15 08:46 UTC, stamepicmorg commented on src/kru.gui/frmMain.cs
> +            //&& Directory.Exists(this.txtOutputClean.Text)
я не столь прошареный за подкапотные игры. но доверюсь тебе.

2023-01-15 08:46 UTC, kasthack commented on src/kru.gui/frmAbout.cs
> +            Process myProcess = new Process();
Fixed @ 000000001de5219a1adb06e76a6e37230c334ac0

2023-01-15 08:46 UTC, kasthack commented on src/kru.gui/frmAbout.cs
> +            Process myProcess = new Process();
Fixed @ 000000001de5219a1adb06e76a6e37230c334ac0

2023-01-15 08:46 UTC, stamepicmorg commented on src/kru.gui/frmMain.cs
> +        var frmabout = new frmAbout();
я не столь прошареный за подкапотные игры. но доверюсь тебе.

2023-01-15 08:46 UTC, kasthack commented on src/kru.gui/frmAbout.cs
> +            Process myProcess = new Process();
Fixed @ 000000001de5219a1adb06e76a6e37230c334ac0

2023-01-15 08:46 UTC, kasthack commented on src/kru.gui/frmAbout.cs
> +            Process myProcess = new Process();
Fixed @ 000000001de5219a1adb06e76a6e37230c334ac0

2023-01-15 08:46 UTC, stamepicmorg commented on src/kru.gui/Command.cs
> +internal record Command(string InputFile, string OutputFile, string OutputFileClean, bool Clean, bool SaveLog,string Bitness)
наверное, я пока сделал так как понял и позвал тебя для ревью ;)

2023-01-15 08:49 UTC, stamepicmorg commented
> В чём смысл файлика build.bat?

* ну я не слежу за трендами и развитием дотнета сейчас. раньше в csproj это работало всрато.
* я из батника перенес настройки в кспрожект
* если можно сделать в кспрожекте такую мультиплатформу с такими же настройками из батника, то будет отлично прям.
* у меня в личном окружение есть народ на х32, мододелы которые используют platform-specific тулы старые. это обосновано.

2023-01-15 08:49 UTC, kasthack commented on src/kru.gui/frmAbout.cs
> +            if (Environment.Is64BitProcess == true && Environment.Is64BitOperatingSystem == true)
@stamepicmorg 

> оно возвращает false если бинарь 32хбитный на 64хбитной системе. с учетом мультисборки, то такое возможно.

Если оно 32 на 64, то у тебя оно свалится на первом условии, т.е. тебе достаточно знать, что процесс 64-битный.

2023-01-15 08:50 UTC, kasthack commented on src/kru.gui/frmAbout.cs
> +        public string archbitness = "x86";
Я сделал в виде свойства в своём коммите.

https://github.com/AntinomyCollective/Retime-Phoneme-Util-GUI/pull/2/files#diff-e5ebd0369c5e0ac334b7e104fcf2f1a8d0063d5136561c7d97b928cbf6be50b6

2023-01-15 08:51 UTC, kasthack commented on src/kru.gui/Command.cs
> +        catch (Exception ex)
Да. Исключение вылетит только при запуске процесса(а вот там у тебя отлова исключений как раз не было)

2023-01-15 08:51 UTC, kasthack approved these changes

2023-01-15 09:14 UTC, merged